name: Build Client

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build Expo app for web
        run: yarn build:web
